EE-1156: update labels for nsps
bcgov/eagle-api pull request #622
Opened 2020-11-13 23:32 UTC by MaxWardle

https://bcmines.atlassian.net/browse/EE-1156

linked to this PR: https://github.com/bcgov/eagle-helper-pods/pull/76

work in progress, creating this PR for visibility while we continue to work on the new dev namespace. The custom-eagle-nsp's have been deployed in dev and might block future work

2020-11-16 16:40 UTC, BcGovNeal approved these changes

2020-11-16 17:07 UTC, marklise commented on openshift/templates/api-minio.dc.yaml
> +        role: minio
We should put this in a variable like`${GOUP_NAME}` above.

2020-11-17 21:30 UTC, mtCarto requested changes
Agree with Mark's comment, the roles should be variables with these as default values

2020-11-18 00:20 UTC, mtCarto approved these changes

2020-11-18 17:50 UTC, merged